on:
  push:
    tags:
      - '**/prd/**'

jobs:
  autoprefix-to-pr:
    runs-on: ubuntu-latest
    name: autoprefixToPR
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set autoprefix
        uses: ./autoprefix-to-pr
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
