on:
  push:
    tags:
      - '**/prd/**'

jobs:
  release-notegen:
    runs-on: ubuntu-latest
    name: releaseNoteGen
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate release note
        uses: ./release-notegen
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
